# Generated by Django 3.1.5 on 2021-02-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in Lari', max_digits=8, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='user',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='%', max_digits=8, null=True, verbose_name='Share per wash'),
        ),
    ]
